[package]
name = "configs"
version = "0.1.0"
edition = "2021"

[dependencies]
lancedb.workspace = true
hyper-util.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-rustls.workspace = true
